project: 
  type: website
  output-dir: docs

website: 
  navbar:
    left: 
      - text: "About me"
        href: page1.qmd
      - text: "Education"
        href: page2.qmd
      - text: "Professional Experience"
        href: page3.qmd
      - text: "Career Goals"
        href: page4.qmd


format: 
  html: 
    theme:
      dark: darkly
      light: flatly 
      
      
    
  
  